version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.11
    working_directory: /
    steps:
      - checkout
      - run:
        name: update-npm
        command: 'npm update -g npm'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
        name: Build App
        command: npm run build
  deploy-job:
    docker:
      - image: circleci/node:8.11
    working_directory: /
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "e4:c2:fd:3b:e6:83:b5:f8:91:51:0d:8f:01:61:dc:de"
      - run:
        name: Run Setup Script
        commnad: bash .circleci/set-upheroku.sh
      - run:
        name: Deploy Master to Heroku
        commnand: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git push heroku master
          fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
        requires:
          - build-job
        filters:
          branches:
            only: master
