# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: /

    steps:
      - checkout
      - run:
        name: update-npm
        command: 'npm update -g npm'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test

      -run:
        name: Build App
        command: npm run build
  -deploy:
    docker:
      -image: circleci/node:8.11
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "e4:c2:fd:3b:e6:83:b5:f8:91:51:0d:8f:01:61:dc:de"
      - run:
        name: Run Setup Script
        commnad: bash .circleci/set-upheroku.sh
      - run:
        name: Deploy Master to Heroku
        commnand: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git push heroku master
          fi

workflows:
  version: 2
  build-deploy:
    jobs:
      -build
      -deploy
        requires:
          -build-job
        filters:
          branches:
            master
